INSERT INTO user(login, password, city_id, type_user_id)
SELECT 'Tatyana', 'radiohead', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Санкт-Петербург' 
AND type_user='Компания' UNION ALL
SELECT 'blablabla', 'blabla', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Москва'
AND type_user='Компания' UNION ALL
SELECT 'company', 'company', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Магнитогорск'
AND type_user='Компания' UNION ALL
SELECT 'ppozitivity', 'blabl', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Томск'
AND type_user='Компания' UNION ALL
SELECT 'Alex', 'max', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Тула'
AND type_user='Компания' UNION ALL
SELECT 'Elina', 'hope', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Владивосток'
AND type_user='Компания' UNION ALL
SELECT 'Oleg', 'friend', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Уфа'
AND type_user='Компания' UNION ALL
SELECT 'termoatom', 'zusik', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Старый Оскол'
AND type_user='Компания' UNION ALL
SELECT 'violetta', 'exit', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Пятигорск'
AND type_user='Компания' UNION ALL
SELECT 'Sunday', 'trip', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Ярославль'
AND type_user='Компания' UNION ALL
SELECT 'bla', 'bla', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Санкт-Петербург'
AND type_user='Компания' UNION ALL
SELECT 'Samara', 'poss', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Самара'
AND type_user='Компания' UNION ALL
SELECT 'root', 'postgres', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Ростов-на-Дону'
AND type_user='Компания' UNION ALL
SELECT 'radio', '79117047632', city_id, type_user_id FROM city FULL JOIN type_user ON city_name='Пенза'
AND type_user='Компания';